In [1]:
# Always import packages first
import pandas as pd
import numpy as np

In [2]:
# A pandas.series having an index is the main difference between a pandas.series and a NumPy array.

# A numpy array
arr = np.random.randn(4) # random values from std normal distribution
print(type(arr))
print(arr, "\n")

# A pandas series made from the previous array
s = pd.Series(arr)
print(type(s))
print(s)

<class 'numpy.ndarray'>
[-1.11267034  1.24811609  0.1630797   1.05213145]

<class 'pandas.core.series.Series'>
0   -1.112670
1    1.248116
2    0.163080
3    1.052131
dtype: float64

In [3]:
# To create a pandas.series you use pd.series

# s = pd.series(data, index = index)

# 'data' parameter can be a list or NumPy array, a python dictionary or a single number, boolean, or string

# the index parameter is optional. if you want to include it, it has to be a list of indices the same length as data

In [4]:
# Creating pandas.series from numpy array

pd.Series(np.arange(3), index=[2023,2024,2025])

2023    0
2024    1
2025    2
dtype: int64

In [5]:
# Creating a pandas.series from a list

pd.Series(['EDS 220', 'EDS 222', 'EDS 223', 'EDS 242'])

0    EDS 220
1    EDS 222
2    EDS 223
3    EDS 242
dtype: object

In [6]:
# You can even create one from a dictionary

d = {'key_0':2, 'key_1':'3', 'key_2':5}
pd.Series(d)

key_0    2
key_1    3
key_2    5
dtype: object

In [7]:
# Creating pandas.series from a single value DEEPLY USEFUL

pd.Series(3.0, index = ['A','B','C'])

A    3.0
B    3.0
C    3.0
dtype: float64

In [13]:
# Even arithmetic operations work on series

s = pd.Series([98,73,65],index=['Andrea', 'Beth', 'Carolina'])

s/10

np.exp(s)

Andrea      3.637971e+42
Beth        5.052394e+31
Carolina    1.694889e+28
dtype: float64

In [14]:
# Now, what about booleans? They are evaluated for each row

s > 70

Andrea       True
Beth         True
Carolina    False
dtype: bool

In [15]:
# Finding na's in a pd.series

s = pd.Series([1, 2, np.nan, 4, np.nan])
s

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

In [ ]:
# How to check for NA's

s.hasnans

# .hasnans says if there are ANY NA's in a series/df

True

In [17]:
# now that we know there are NA's, we can check which rows have them

s.isna()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [23]:
# Check-in 1

nines = pd.Series([1,2,-999,-999], index= ['A','B','C','D'])

nines.mask(nines < 0)

A    1.0
B    2.0
C    NaN
D    NaN
dtype: float64

In [25]:
# Creating a pandas df using dictionaries

d = {'col_name_1' : pd.Series(np.arange(3)),
    'col_name_2' : pd.Series([3.1,3.2,3.3])}

df = pd.DataFrame(d)
df

   col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

In [26]:
# Can change index using df.Index

df.index = ['a','b','c']
df

   col_name_1  col_name_2
a           0         3.1
b           1         3.2
c           2         3.3

In [27]:
# Check in # 2

df.columns = ['beautiful','gorg']